apiVersion: v1
kind: Service
metadata:
  name: node-pod-grouper
spec:
  selector:
    app: node-pod-grouper
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Container port
  type: ClusterIP
